"""user_id and table_id now unique

Revision ID: c4a27220be13
Revises: fd7077ce4dd3
Create Date: 2026-02-05 17:15:45.857925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4a27220be13'
down_revision: Union[str, Sequence[str], None] = 'fd7077ce4dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bookings', ['user_id'])
    op.create_unique_constraint(None, 'bookings', ['table_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='unique')
    op.drop_constraint(None, 'bookings', type_='unique')
    # ### end Alembic commands ###
